// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2WN7700456IXRmm_usgvmHeI9GYxK8o',
    appId: '1:578477993346:web:48b93b1b8e660b6660739b',
    messagingSenderId: '578477993346',
    projectId: 'trainingapp-cb12b',
    authDomain: 'trainingapp-cb12b.firebaseapp.com',
    storageBucket: 'trainingapp-cb12b.appspot.com',
    measurementId: 'G-JS8YX2K95J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvIQcR7KyZyooHGGC7U-iL_-FKyauZtg',
    appId: '1:578477993346:android:c9bbc06ff9cddfb860739b',
    messagingSenderId: '578477993346',
    projectId: 'trainingapp-cb12b',
    storageBucket: 'trainingapp-cb12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3Bu4-gKV-Fx_ELaVErfyafKy9YGnSR0',
    appId: '1:578477993346:ios:6e517bbb0da1c0d760739b',
    messagingSenderId: '578477993346',
    projectId: 'trainingapp-cb12b',
    storageBucket: 'trainingapp-cb12b.appspot.com',
    iosBundleId: 'com.example.studiosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3Bu4-gKV-Fx_ELaVErfyafKy9YGnSR0',
    appId: '1:578477993346:ios:6e517bbb0da1c0d760739b',
    messagingSenderId: '578477993346',
    projectId: 'trainingapp-cb12b',
    storageBucket: 'trainingapp-cb12b.appspot.com',
    iosBundleId: 'com.example.studiosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVsXWnJyO0Mhu_f-zn3ljmYWR2qgAp1aU',
    appId: '1:578477993346:web:b0a139c89394026b60739b',
    messagingSenderId: '578477993346',
    projectId: 'trainingapp-cb12b',
    authDomain: 'trainingapp-cb12b.firebaseapp.com',
    storageBucket: 'trainingapp-cb12b.appspot.com',
    measurementId: 'G-F5FTFJHDWF',
  );
}
